### ISSUE TITLE
UI Design update

### ISSUE THREAD

**Issue by eraygundogmus** [opensource-place/backend#62]
I had some positional changes on landing page. Some animations added.
New logo added.  

https://user-images.githubusercontent.com/74984741/104830105-909ff580-588c-11eb-8045-c84d14536fd1.mp4

**Comment by eraygundogmus** [comment]
Projects Page Updates

https://user-images.githubusercontent.com/74984741/104831796-1166ed80-589d-11eb-8134-ff432b434a7b.mp4

**Comment by eraygundogmus** [comment]
> Projects Page Updates
> 
>  projects.mp4

I believe we need to use a pagination on this page.

**Comment by altaysimsek** [comment]
Abi o logo niye öyle uçup kaçıyor 😂 o şekilde kalmayacak değil mi

**Comment by eraygundogmus** [comment]
statik de durabilir ya da animasyon değiştirilebilir, logonun bu tarz animate potansiyeli var onu gösterdim niyetim uçurup kaçırmak değildi 👍 

> Abi o logo niye öyle uçup kaçıyor 😂 o şekilde kalmayacak değil mi
